### ISSUE TITLE
Build notification link points to wrong IP

### ISSUE THREAD

**Issue by kkaung** [PeteGoo/tcSlackBuildNotifier#125]
We have TeamCity setup on an AWS EC2 instance.  Initially setup was fine.  All notifications on our Slack channel went to the IP of the EC2 instance to the corresponding build.  We had to upgrade our EC2 instance recently which also changed IP.  Now our notifications point to the old IP instead of the new.  Not sure where to go to change this.

**Comment by pointerxr** [comment]
Hi @kkaung,

I don't think this problem is a bug in the plugin, we do use SBuildServer to obtain the root IP Address.

			´setBuildStatusUrl(server.getRootUrl() + "/viewLog.html?buildTypeId=" + 
buildType.getBuildTypeId() + "&buildId=lastFinished");´

**Comment by pointerxr** [comment]
Check this as well: https://confluence.jetbrains.com/display/TCD10/Configuring+Server+URL

**Comment by kkaung** [comment]
I had a feeling it was on TC!  I couldn't find that setting.  Thank you @pointerrr!
