### ISSUE TITLE
Do not split commit descriptions into several lines

### ISSUE THREAD

**Issue by enricmarques** [PeteGoo/tcSlackBuildNotifier#129]
I don't know if this is a Slack API Attachment issue, or a tcSlackBuildNotifier issue, but in the list of commits, the description is truncated (like if there were a 80-characters limit).

![capture](https://cloud.githubusercontent.com/assets/903431/20091943/af775588-a595-11e6-9ac6-0e76a9554a37.PNG)

**Comment by pointerxr** [comment]
Can u give me an example of a full commit message? (according to your screenshot)

I don't speak spanish so I don't really see what's the problem here

**Comment by enricmarques** [comment]
When I say truncated, I mean that the text has been split in two lines, when I fits in a single line.

**Comment by pointerxr** [comment]
@enricmarques 

I'm sorry but we don't split the commit messages. 

We use the following code which takes the full commit description:

`sbCommits.append(String.format("%s :: %s :: %s\n", revision.substring(0, Math.min(revision.length(), 10)), commit.getUserName(), commit.getDescription()));`

Here are examples of Slack attachements that are too long, they do get splitted by Slack: https://api.slack.com/docs/message-attachments#attachment_structure

**Comment by pointerxr** [comment]
I will close this issue as we cannot do anything about how Slack handles attachements.
