### ISSUE TITLE
Triggering custom notification from command line / build script

### ISSUE THREAD

**Issue by iwasrobbed** [PeteGoo/tcSlackBuildNotifier#132]
In scenarios where the build script has custom output, such as code coverage reporting, it would be nice if we could trigger a custom Slack notification to be sent from a build script. In this example, something like "Code coverage is now: 92.1%"

Would this be possible?

Seems like a possible duplicate of https://github.com/PeteGoo/tcSlackBuildNotifier/issues/63

**Comment by PeteGoo** [comment]
I think this would be pretty hard to do from a script. Unless someone else has an idea?
