### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by philjones88** [PeteGoo/tcSlackBuildNotifier#17]
Hi,

I've been trying to integrate this plugin with TeamCity but following the documentation is problematic.
I can't see a way to generate an OAuth token like shown.
I've tried creating a bot to obtain a token but this doesn't seem to work.
Also could you expand on:

* your team name
Could we have some examples? E.g. is it just "Foo" or "foo.slack.com" ?

* defaultChannel
Could you say if it needs the leading # ?

It would also be handy if there was a "send a test notification" button rather than triggering builds to try and get it working.

**Comment by jchannon** [comment]
+1

**Comment by PeteGoo** [comment]
Hi, sorry for the delay.

The team name is just foo, channels should be prefixed with a #.

For the token, go to https://api.slack.com/web and look down the page for a way to generate the token (of you haven't already)

**Comment by PeteGoo** [comment]
The latest release [1.2.0](https://github.com/PeteGoo/tcSlackBuildNotifier/releases/tag/1.2.0) now has a test notification button in the new Admin page.
