### ISSUE TITLE
Proxy settings are not working

### ISSUE THREAD

**Issue by uldissturms** [PeteGoo/tcSlackBuildNotifier#19]
Proxy settings are not taken into account when provided in expected format:
```xml
 <proxy host="myproxy.mycompany.com" port="8080">
      <noproxy url=".mycompany.com" />
      <noproxy url="192.168.0." />
    </proxy>
```

This down to how SlackNotificationListener sets proxy for slackNotification in getFromConfig method. This is not the only problem though, still investigating.

**Comment by PeteGoo** [comment]
Can we close this now?

**Comment by uldissturms** [comment]
Yep, should be working now. Cheers mate! There are a couple things I'm currently working on since our proxy server is... well special. To add proxy auth please take a look at this commit: https://github.com/uldissturms/tcSlackBuildNotifier/commit/dc6dacba481e648c509397bff78f7556a1d53d86. Just ignore the hardcoded scheme bit 
```java
.setProxy(new HttpHost(proxyHost, proxyPort, "http")); 
```
should be 
```java
.setProxy(new HttpHost(proxyHost, proxyPort)); 
```
to use https proxy for https.

**Comment by PeteGoo** [comment]
No worries. I'll close this then.
