### ISSUE TITLE
Consider using incoming webhooks for integration

### ISSUE THREAD

**Issue by mfloryan** [PeteGoo/tcSlackBuildNotifier#22]
Rather than using oauth for a particular user perhaps the integration could be done via the incoming webhooks
https://api.slack.com/incoming-webhooks

**Comment by PeteGoo** [comment]
This should actually be supported. The documentation probably just needs to be udpated

**Comment by PeteGoo** [comment]
This has now been tested and should work in the the newest release 

[1.2.0](https://github.com/PeteGoo/tcSlackBuildNotifier/releases/tag/1.2.0)
