### ISSUE TITLE
Teamcity 9

### ISSUE THREAD

**Issue by cobrowserAlex** [PeteGoo/tcSlackBuildNotifier#25]
I have installed the plugin successfully in tramcity 9.0:
```
tcSlackBuildNotifier-master	n/a	n/a	<TeamCity Data Directory>/.unpacked/tcSlackBuildNotifier-master
```
But I can't find it anywhere. Is it supposed to work in TC9?

**Comment by PeteGoo** [comment]
It should do. Which release did you download? Did you drop the zip file into the plugins folder or upload it via the web ui?

**Comment by PeteGoo** [comment]
I've just tested the latest (1.2.0) with TC 9.0.2 and seems to install fine and the admin page shows up correctly. I would still love to know your scenario though.

**Comment by cobrowserAlex** [comment]
hmm i'll give it atry again

**Comment by cobrowserAlex** [comment]
It's my own stupidity -> rtfm
I didn't put the realease zip, but i put the zip of the repo in the plugins dir.
Works like a charm.
Thanks and sorry

**Comment by PeteGoo** [comment]
No worries. Glad it's now working
