### ISSUE TITLE
truststore issues 

### ISSUE THREAD

**Issue by mobilitus-buildmaster** [PeteGoo/tcSlackBuildNotifier#29]
thanks for neat plugin.

I had some trust issues with the setup (teamcity 9 on a mac mini with a fresh yosemite install)

These guidelines resolved them for me 

http://stackoverflow.com/questions/4764611/java-security-invalidalgorithmparameterexception-the-trustanchors-parameter-mus

(so not an issue, just a note to save someone some time)

**Comment by PeteGoo** [comment]
Can you elaborate on your scenario and which answer was the resolution? I'll add it to the docs

**Comment by mobilitus-buildmaster** [comment]
I installed tcSlackBuildNotifier the recommended way on a Mac Mini, with a fresh Yosemite install (with java 1.6  Apple distro).  Key o is that the keystore was empty.

The UI only gave me vague error messages when I tried to send a test message (message could not be sent), but in one of the logs (don't remember which one)  I saw "java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty".

I fixed this by   

    cd $JAVA_HOME/Contents/Home/jre/lib/security
    ln -s /System/Library/Java/Support/CoreDeploy.bundle/Contents/Home/lib/security/cacerts
    ln -s /System/Library/Java/Support/Deploy.bundle/Contents/Home/lib/security/blacklist 
    ln -s /System/Library/Java/Support/Deploy.bundle/Contents/Home/lib/security/trusted.libraries

**Comment by PeteGoo** [comment]
I've [written it up in a FAQ](https://github.com/PeteGoo/tcSlackBuildNotifier/wiki/FAQ#i-get-a-javasecurityinvalidalgorithmparameterexception-the-trustanchors-parameter-must-be-non-empty-error). Can you have a look and close this issue if you are happy?

**Comment by mobilitus-buildmaster** [comment]
looks good :+1:
