### ISSUE TITLE
"Only trigger when build changes from Success to Failure" not saving

### ISSUE THREAD

**Issue by ZevEisenberg** [PeteGoo/tcSlackBuildNotifier#37]
I have "Trigger when build Fails" enabled on a project, and I want to enable the sub-checkbox "Only trigger when build changes from Success to Failure". So I check the box, click Save. If I close the configuration popup and then open it again, the box remains checked, but if I refresh the page and then click Edit again, that box reverts to unchecked. All of the other boxes seem to be saving correctly.

**Comment by PeteGoo** [comment]
Yup this sounds like a bug. What version are you on?

**Comment by ZevEisenberg** [comment]
TeamCity 8.1.4
tcSlackBuildNotifier 1.4.0

**Comment by PeteGoo** [comment]
Wicked. Thanks so much for reporting this. I'll have a look and let you know the result

**Comment by ansel1** [comment]
I've seen this too.  Seeing it since at least 1.2 (on 1.4 now)

**Comment by PeteGoo** [comment]
Fixed in [1.4.1](https://github.com/PeteGoo/tcSlackBuildNotifier/releases/tag/1.4.1) 

Check it out and let me know if it's all good. Thanks again.
