### ISSUE TITLE
TeamCity 9 support

### ISSUE THREAD

**Issue by hmemcpy** [PeteGoo/tcSlackBuildNotifier#38]
Unfortunately, this very excellent plugin seems to be broken on TeamCity 9 (I'm using 9.0.3).
The 'Slack Notifications' menu is missing from the Administration page (the Slack configuration dialog still works, though)...

**Comment by PeteGoo** [comment]
I'll have a look now. I've been testing on 9.0.2.

**Comment by PeteGoo** [comment]
Can you quickly check if there are any error messages in the teamcity-server.log file?

**Comment by PeteGoo** [comment]
Just tested with TeamCity 9.0.3 (build 32334) and all seemed good. 

Can you see if you can get something meaningful from the logs in the Diagnostics section? You may have to switch on debug logging there.

**Comment by hmemcpy** [comment]
Oh god, I'm sorry :disappointed: 
It seems that we had a very old version of this plugin running, and TC was upgraded this morning from v8.
I just placed the latest version of the plugin (1.4.1), and everything works great again in TC9.

Sorry for the bother, and thanks!

**Comment by PeteGoo** [comment]
Hey, no worries. Glad you are enjoying the plugin.
