### ISSUE TITLE
Does not work on TeamCity 8.0.5

### ISSUE THREAD

**Issue by borismod** [PeteGoo/tcSlackBuildNotifier#41]
I configured everything as required, "test connection" worked fine. I've added my slack username on the Notifications page and configured a Slack Notification. It does not send any notifications.

**Comment by jaroslavurban** [comment]
Check the Slack tab as well on Project page, not only in user notification setting. Once I configured notification at project level, it starts working. Hope it helps.

**Comment by borismod** [comment]
@jaroslavurban thank you for your quick reply. Do you mean on the notifications page? I configured like this, and it still does not work:
![image](https://cloud.githubusercontent.com/assets/209971/7047327/7cff8fa2-de14-11e4-9c1d-b4228cb4726a.png)
Any idea?

**Comment by jaroslavurban** [comment]
that is just first step, now you need to set it as well at project, see screenshot. 

![tc_slack](https://cloud.githubusercontent.com/assets/1242980/7048148/6959a85a-de11-11e4-8573-722f4030c93f.png)

**Comment by borismod** [comment]
Thanks! Yes, it started working! Thanks for the quick reply!
