### ISSUE TITLE
Slack tab always says "no notifications configured", but they are

### ISSUE THREAD

**Issue by judgeaxl** [PeteGoo/tcSlackBuildNotifier#58]
Using TeamCity 9.1.3 on OS X, the slack tab for any project always says there are no configured notifications, however, clicking "add project slack notifications" will correctly list the configured notifications. I'm using version 1.4.2.

**Comment by PeteGoo** [comment]
Hmmm. Strange. Seems to work on Ubuntu.

**Comment by judgeaxl** [comment]
This might have been related to me having several levels of sub-projects and the two top levels not having any build configurations. It's working well enough right now.

 However, the setup process is a bit awkward, perhaps due to limitations in Team City's plugin model, but there are just too many clicks to get to what I need, IMHO.

**Comment by PeteGoo** [comment]
Just out of interest does this sound like the setup process?
- Download the zip
- Go to Plugins in Administration
- Upload the zip
- Restart the service
- Configure Slack Notifications Administration page
- Then configure projects

Not sure what I can do about the first 4. Could be some improvements in the experience for the last two.

**Comment by pointerxr** [comment]
Please open a new issue if you believe the setup process is awkward as it is not related to the issue you describe in the original description.

Or just tell me here and I do it for you.

For now I close this as it seems to be pretty old.
