### ISSUE TITLE
Notification link to Build Log does not include port number

### ISSUE THREAD

**Issue by aarndt** [PeteGoo/tcSlackBuildNotifier#61]
Hello,

Our team city instance is served from a port other than 80. The Build Log URL in the slack notification does not include the port. 

It appears that JetBrains' SBuildServer class does not expose a way of retrieving the port. Perhaps a custom field can be added to the plugin to specify the build server port (default to 80 if blank)

**Comment by aarndt** [comment]
Apologies. This was a configuration miss on my side. As long as the build server URL is set correctly in Team City Global Settings (with the port), the link will work correctly. 

Closing issue.

**Comment by PeteGoo** [comment]
Glad you got it sorted.
