### ISSUE TITLE
Content tab changes are not saved if configured on the project level

### ISSUE THREAD

**Issue by rhevesi-lmi** [PeteGoo/tcSlackBuildNotifier#65]
Hi, 
Notifications work fine if I configure them on a project level, however when I change anything on the "Content" tab and save, the changes does not get saved. If I open the Content tab again, the default settings are displayed. Configuration file under pluginData folder remain untouched. 
I tried to enable the "Show failure reason" option, but it seems none of the settings can be changed.
The same options seem to be fine when configured globally. Teamcity version: 9.1.3 on Windows Server 2012.

**Comment by KunalKapadia** [comment]
+1

**Comment by slipdef** [comment]
General tab changes are not saved as well for me (9.1.4)

**Comment by PeteGoo** [comment]
Weird. I've managed to repro it. Looking into it.

**Comment by PeteGoo** [comment]
Ok. Found the issue. Creating a fix now

**Comment by PeteGoo** [comment]
Hi folks, please try the latest release. Sorry for the inconvenience.

https://github.com/PeteGoo/tcSlackBuildNotifier/releases/tag/1.4.4

**Comment by rhevesi-lmi** [comment]
I tried and the problem is still the same. However I think there must be some problem with the released zip file, because all class files are identical inside the jar. Only some text files containing the version number are different.

**Comment by rhevesi-lmi** [comment]
Building the plugin from source fixes the problem so the fix is right, only the released zip file is wrong. Please replace the zip :) Thanks, Pete!

**Comment by PeteGoo** [comment]
@rhevesi-lmi  I've rebuilt and updated the zip file on the release.

**Comment by rhevesi-lmi** [comment]
It is fixed now, thanks!
