### ISSUE TITLE
API Token asked on every notification setup

### ISSUE THREAD

**Issue by jon-karnofsky-abt** [PeteGoo/tcSlackBuildNotifier#72]
When adding a new notification on a project, the API Token is a listed field every time - it doesn't inherit the API Token setup in the administration area.  In the screenshot on the main GitHub page, in the "Slack Config" tab, the first field is the Channel, which makes sense, and what I'd expect to see.

Is there a configuration that is keep our admin settings API Token to be used, forcing us to put in the token on each project config?

Thanks much.We're on TeamCity 9.1.6 and notifier 1.4.4

**Comment by jon-karnofsky-abt** [comment]
![image](https://cloud.githubusercontent.com/assets/16245481/13115564/44ab8332-d566-11e5-8e30-d72c7b8f8d61.png)

**Comment by PeteGoo** [comment]
Is it set in Global Administration -> Slack tab?

**Comment by PeteGoo** [comment]
If that works then I think we need to tell people on this page where they can set it globally

**Comment by pointerxr** [comment]
same issue as #60

**Comment by pointerxr** [comment]
closed see #60
