### ISSUE TITLE
Am I blind? Configure Project Notifications

### ISSUE THREAD

**Issue by wacamoe** [PeteGoo/tcSlackBuildNotifier#73]
Hello,
   Not sure if this is an issue or I am blind, but I cannot locate where to configure project notifications. I am using TeamCity 9.1.3 and only see:

![image](https://cloud.githubusercontent.com/assets/1175063/13509280/7a62d7b6-e13f-11e5-8299-f1156ba5c9e3.png)

**Comment by PeteGoo** [comment]
Hey just go to the project configuration home (where the history and stats are) and look for the Slack tab

**Comment by wacamoe** [comment]
It took me a bit - but I found it!
