### ISSUE TITLE
a canceled build is misreported as 'Running'

### ISSUE THREAD

**Issue by mr-fixit** [PeteGoo/tcSlackBuildNotifier#74]
When a build is canceled, the notification to Slack says 'Running - ...', I expected 'Canceled - ...'.

Seems like there should be a BUILD_STATUS_CANCELED variable, and that SlackNotificationPayloadContent.java:258, AKA setBuildResult() should use it.

**Comment by pointerxr** [comment]
Thanks for reporting this @mr-fixit 

I got your point and this indeed seem to be a bug, as you have already said what needs to be done would you mind do a PR?

**Comment by pointerxr** [comment]
Right now the Notificator interface doesnt message us when the build status is actually canceled.

This might be added in a future version of the API.
