### ISSUE TITLE
Support for @-notifying user that triggered the build?

### ISSUE THREAD

**Issue by rameshdharan** [PeteGoo/tcSlackBuildNotifier#76]
It'd be great if we could directly notify the user (if any) who triggered a build, when that build fails. 

I tried adding a notification for @%teamcity.build.triggeredBy.username% but it appears that there's no TeamCity variable expansion pass before generating the Slack notification.

**Comment by mcctomsk** [comment]
It's looks like a bug. I've filled in "Slack Username" field for each developer account in TeamCity and set rules for project notifications in Slack tab to "True" on both "@channel" & "Slack User (if known)" in "mention on first failure" field. However, TeamCity BOT only mentions the @channel, but not a Slack user. I've tried to set Administration -> Users -> %username% -> Slack notifications to notify on "Builds with my changes" for both "Build is successful" and "Build fails" but it isn't working too.

And why TeamCity BOT prints after words "Changes By" as name of user as a part of his email address before @ sign?

**Comment by pointerxr** [comment]
@mcctomsk do you have a real example of such a post?

**Comment by mcctomsk** [comment]
@pointerxr now I think may be it's not a TeamCity problem. We use visual studio online and its git repository with turned on "Alternate authentication credentials". We've one of users who commit changes to git from only one computer and when TeamCity build new build each time we've in slack message with one of **three** variant of users name: "Changes By dgo" or "Changes By d.f.goryunov" or Changes By dmitry goryunov". If commit was pushed by another one user in slack we've message "Changes by" or "anp" or "Andrei". And we can't find dependency. 
![image](https://cloud.githubusercontent.com/assets/6916600/17540195/7c579e9a-5ede-11e6-9d84-84de3644e296.png)
![image](https://cloud.githubusercontent.com/assets/6916600/17540219/9fcc2e72-5ede-11e6-8012-7f91a8789d4f.png)

**Comment by mcctomsk** [comment]
@pointerxr thanks! Your question made me analyze the problem more deeply. Now I found that it depends from a IDE which developers use. If they use VS we get name from profile in visual studio online, if something else we get only right part from e-mail.

**Comment by pointerxr** [comment]
@mcctomsk I guess that's good to know then! Is there any relation now to this issue or something that needs to be changed on our side?

**Comment by mcctomsk** [comment]
I don't have any questions after I reread this article https://github.com/PeteGoo/tcSlackBuildNotifier/wiki/User-Configuration. Thanks!

**Comment by pointerxr** [comment]
Closed then :)
