### ISSUE TITLE
Icon scaling issues

### ISSUE THREAD

**Issue by thedataking** [PeteGoo/tcSlackBuildNotifier#79]
Hi, thanks for all your hard work! I got slack notifications up and running just fine. However, the icon looks very bad (after scaling I presume) – see the attached image. I'm using the default [TC logo](https://raw.githubusercontent.com/PeteGoo/tcSlackBuildNotifier/master/docs/TeamCity.png). 

<img width="122" alt="tc_icon" src="https://cloud.githubusercontent.com/assets/4011337/14480871/ee68b632-00e1-11e6-881d-4edf42c474d1.png">

**Comment by PeteGoo** [comment]
Ugh. Anyone else seeing this?

**Comment by squalsoft** [comment]
Yes, problem exists on custom images too.

**Comment by kblanks** [comment]
I've found that uploading the desired icon to Slack directly (via the integration configuration) and then entering `.` into the image URL bit of the plugin works.

![plugin config](https://i.imgur.com/gHBbhY0.png)
![slack output](https://i.imgur.com/BI8sKRm.png)

**Comment by PeteGoo** [comment]
Hmmm. Must be just a resizing problem. Maybe a manually resized image will work

**Comment by bondarewicz** [comment]
I've used @kblanks solution and manually uploaded the logo into _Integration Settings -> Customize Icon_

**Comment by thedataking** [comment]
@kblanks @bondarewicz I'm not sure what this procedure is... would you mind elaborating? thanks!

**Comment by PeteGoo** [comment]
Try using the 72x72 image I have just uploaded.
https://raw.githubusercontent.com/PeteGoo/tcSlackBuildNotifier/master/docs/TeamCity72x72.png

**Comment by PeteGoo** [comment]
Updated in [1.4.5](https://github.com/PeteGoo/tcSlackBuildNotifier/releases/tag/1.4.5)

**Comment by thedataking** [comment]
Thanks! Works with the new 72x72 image. Still seeing scaling issues using old icon.

**Comment by pointerxr** [comment]
closed
