### ISSUE TITLE
Is there any way to configure slack at a template level?

### ISSUE THREAD

**Issue by Myster** [PeteGoo/tcSlackBuildNotifier#88]
We have lots of small projects and it would be great to configure slack at a template level.
Is this possible?
Cheers.
Murray.

**Comment by PeteGoo** [comment]
Like in #62 ? Or different?

**Comment by Myster** [comment]
I'm not sure, I just would like a blanket failed build notification for all projects, but I'm not sure how to set that up if it's possible. (I was thinking I'd set it up in a Build Configuration Template, but anywhere to achieve the result is fine :-)

**Comment by PeteGoo** [comment]
Ah, ok. Yeah that has been a long standing request #13.

Hmmm. That might have to be a thing then

**Comment by Myster** [comment]
Oh yea, great :-) I'll thumbs up on that one. :-)

**Comment by pointerxr** [comment]
Closing this in favor of #13 then.
